# This is a example configuration file for the imag suite.
# It is written in TOML

[store]

# Set to false if you do not want imag to create the directory where the store
# lives implicitely
implicit-create = false

# Hooks which get executed right before the Store is closed.
# They get the store path as StoreId passed, so they can alter the complete
# store, so these hooks should be chosen carefully.
store-unload-hook-aspects  = [ "debug" ]

pre-create-hook-aspects    = [ "debug" ]
post-create-hook-aspects   = [ "debug" ]

pre-move-hook-aspects      = [ "debug" ]
post-move-hook-aspects     = [ "debug" ]

pre-retrieve-hook-aspects  = [ "debug" ]
post-retrieve-hook-aspects = [ "debug" ]

pre-update-hook-aspects    = [ "debug" ]
post-update-hook-aspects   = [ "debug" ]

pre-delete-hook-aspects    = [ "debug" ]
post-delete-hook-aspects   = [ "debug" ]

[store.aspects.debug]
parallel = false
mutable_hooks = true

[store.hooks.stdhook_debug]
aspect = "debug"

