[package]
name = "libimagtodo"
version = "0.1.0"
authors = ["mario <mario-krehl@gmx.de>"]

[dependencies]
semver = "0.2"
task-hookrs = { git = "https://github.com/mario-kr/task-hookrs.git" }
uuid = "0.2.0"
toml = "0.1.28"

[dependencies.libimagstore]
path = "../libimagstore"

[dependencies.libimagerror]
path = "../libimagerror"

